import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Theme from "@/components/Theme";
import { Toaster } from "sonner";
import { AuthProvider } from "@/components/AuthProvider";

import ProviderComponent from "@/components/ProviderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderComponent>
          <AuthProvider>
            <Theme>
              <Navbar />
              {children}
              <Toaster />
            </Theme>
          </AuthProvider>
        </ProviderComponent>
      </body>
    </html>
  );
}
