import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Theme from "@/components/Theme";

import ProviderComponent from "@/components/ProviderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderComponent>
        <Theme>
          <Navbar />
          {children}
        </Theme>
      </ProviderComponent>
    </html>
  );
}
